name: CLI Automated Release
on:
  push: 
  # workflow_dispatch:
  #   inputs:
  #     releaseVersion:
  #       description: "The version number of the new release"
  #       required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Testing flow start
        run: echo "Workflow Started"
    
      - name: Check out turbot-core
        uses: actions/checkout@master
        with:
          repository: turbotio/turbot-core
          token: ${{ secrets.turbot_core_pac }}
          ref: master

      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_KEY }}
      #     name: id_rsa
      #     known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Cache HIT/MISS
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

          
      - name: Install npm packages
        run: |
          rm package-lock.json
          npm ci
          echo ::set-env name=PATH::"$PATH:$(pwd)/node_modules/.bin"
          echo ::set-env name=NODE_PATH::"${{ github.workspace }}/lib"

      # - name: Delete SSH key
      #   run: find ~/.ssh -type f -exec shred -uf {} \;

      - name: Build CLI
        run: |
          echo $PATH
          ls node_modules/.bin/nexe
          cd lib/@turbot/cli
          ./compile.sh

      # - name: Install CLI
      #   run: |
      #     cd lib/@turbot/cli/dist
      #     unzip *linux*
      #     echo ::set-env name=PATH::"$PATH:$(pwd)"
      #     cd -

      # - name: Read package.json
      #   uses: tyankatsu0105/read-package-version-actions@v1
      #   id: package-version
      #   with:
      #     path: lib/@turbot/cli

      # - name: Show version number
      #   run: echo "Version is ${{ steps.package-version.outputs.version }}"
  