name: CLI Automated Release
on:
  push:
  # workflow_dispatch:
  #   inputs:
  #     releaseVersion:
  #       description: "The version number of the new release"
  #       required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # if we don't do this, Git will convert all line endings to CRLF when cloning on windows
      - name: Set Git to use Linux-style line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out turbot-core
        uses: actions/checkout@master
        with:
          repository: turbotio/turbot-core
          token: ${{ secrets.turbot_core_pac }}
          ref: master
          submodules: true

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache HIT/MISS
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}

      - name: Install npm packages
        run: |
          npm install
          echo ::set-env name=PATH::"$PATH:$(pwd)/node_modules/.bin"
          echo ::set-env name=NODE_PATH::"$GITHUB_WORKSPACE/lib"

      - name: Build CLI Binaries
        run: |
          echo $PATH
          echo $NODE_PATH
          ls $GITHUB_WORKSPACE/node_modules/.bin/nexe
          cd $GITHUB_WORKSPACE/lib/@turbot/cli
          ./compile.sh

      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
        with:
          path: lib/@turbot/cli

      - name: Show version number
        run: echo "Version is ${{ steps.package-version.outputs.version }}"

      - name: Move build artifacts
        run: |
          mkdir ~/artifacts
          mv $GITHUB_WORKSPACE/lib/@turbot/cli/dist/turbot_cli_${{ steps.package-version.outputs.version }}_windows_amd64.zip ~/artifacts/windows.zip
          mv $GITHUB_WORKSPACE/lib/@turbot/cli/dist/turbot_cli_${{ steps.package-version.outputs.version }}_linux_amd64.zip ~/artifacts/linux.zip
          mv $GITHUB_WORKSPACE/lib/@turbot/cli/dist/turbot_cli_${{ steps.package-version.outputs.version }}_darwin_amd64.zip ~/artifacts/darwin.zip

      - name: Zip up Acceptance Test Suite
        run: |
          mv $GITHUB_WORKSPACE/lib/@turbot/cli/test ~/tests
          cd ~/tests
          zip -r ~/artifacts/tests.zip .
          cd -

      - name: List Build Artifacts
        run: ls -l ~/artifacts

      - name: Save Windows Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-windows
          path: ~/artifacts/windows.zip
          if-no-files-found: error

      - name: Save Linux Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-linux
          path: ~/artifacts/linux.zip
          if-no-files-found: error

      - name: Save Windows Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-darwin
          path: ~/artifacts/darwin.zip
          if-no-files-found: error

      - name: Save Acceptance Test Suite
        uses: actions/upload-artifact@v2
        with:
          name: test-artifact
          path: ~/artifacts/tests.zip
          if-no-files-found: error

    outputs:
      version: ${{ steps.package-version.outputs.version }}

  acceptance_tests:
    name: Run Acceptance Tests on ${{ matrix.platform }}
    needs: build

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TURBOT_CLI_ACC_PROFILE: acceptance_test_profile
      TURBOT_CLI_ACC_REGISTRY: turbot-stg.com
      TURBOT_CLI_ACC_ACCESS_KEY: ${{ secrets.TURBOT_CLI_ACC_ACCESS_KEY }}
      TURBOT_CLI_ACC_SECRET_KEY: ${{ secrets.TURBOT_CLI_ACC_SECRET_KEY }}
      TURBOT_CLI_ACC_WORKSPACE: ${{ secrets.TURBOT_CLI_ACC_WORKSPACE }}
      TURBOT_CLI_ACC_REGISTRY_USER: ${{ secrets.TURBOT_CLI_ACC_REGISTRY_USER }}
      TURBOT_CLI_ACC_REGISTRY_PASS: ${{ secrets.TURBOT_CLI_ACC_REGISTRY_PASS }}

    steps:
      - name: Setting up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Nunjucks CLI
        run: |
          npm install -g nunjucks-cli

      - name: Prepare for downloads
        id: prepare-for-downloads
        run: |
          mkdir ~/artifacts

      # - name: Download Windows Build Artifacts
      #   uses: actions/download-artifact@v2
      #   if: ${{ matrix.platform == 'windows-latest' }}
      #   with:
      #     name: build-artifact-windows
      #     path: ~/artifacts

      - name: Download Linux Build Artifacts
        uses: actions/download-artifact@v2
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        with:
          name: build-artifact-linux
          path: ~/artifacts

      - name: Download Darwin Build Artifacts
        uses: actions/download-artifact@v2
        if: ${{ matrix.platform == 'macos-latest' }}
        with:
          name: build-artifact-darwin
          path: ~/artifacts

      - name: Download Acceptance Test Suite
        uses: actions/download-artifact@v2
        with:
          name: test-artifact
          path: ~/artifacts

      - name: Check that everything got downloaded
        run: |
          ls -l ~/artifacts
          
      - name: Rename build artifact on Darwin
        if: ${{ matrix.platform == 'macos-latest' }}
        run: mv ~/artifacts/darwin.zip ~/artifacts/build.zip
          
      - name: Rename build artifact on Linux
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: mv ~/artifacts/linux.zip ~/artifacts/build.zip

      - name: Check that renaming is good
        run: |
          ls -l ~/artifacts

      - name: Extract Artifacts and Install Binary
        if: ${{ matrix.platform == 'macos-latest' || matrix.platform == 'ubuntu-latest' }}
        run: |
          mkdir ~/build
          mkdir ~/tests
          unzip ~/artifacts/build.zip -d ~/build
          unzip ~/artifacts/tests.zip -d ~/tests
          ls -l ~/build
          ls -l ~/tests
          echo ::set-env name=PATH::"$PATH:$HOME/build"

      - name: Setup Config Dir
        run: |
          mkdir -p $HOME/.config/turbot
          touch $HOME/.config/turbot/config.yml
          touch $HOME/.config/turbot/credentials.yml
          touch $HOME/.config/turbot/registry.yml

      - name: Run Tests
        if: ${{ matrix.platform == 'macos-latest' || matrix.platform == 'ubuntu-latest' }}
        run: |
          chmod +x $HOME/tests/run_acceptance.sh
          $HOME/tests/run_acceptance.sh

  create_release:
    name: Create Release
    needs: [build, acceptance_tests]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Do Nothing
        run: echo "Do Nothing"

  upload_release_assets:
    name: Upload Release assets
    needs: create_release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Do Nothing
        run: echo "Do Nothing"

  clean_up:
    name: Clean Up Artifacts
    needs: upload_release_assets
    runs-on: ubuntu-latest
    steps:
      - name: Clean up Windows Build
        uses: geekyeggo/delete-artifact@v1
        with:
          name: build-artifact-windows
          failOnError: true

      - name: Clean up Linux Build
        uses: geekyeggo/delete-artifact@v1
        with:
          name: build-artifact-linux
          failOnError: true

      - name: Clean up Darwin Build
        uses: geekyeggo/delete-artifact@v1
        with:
          name: build-artifact-darwin
          failOnError: true

      - name: Clean up Test Suite
        uses: geekyeggo/delete-artifact@v1
        with:
          name: test-artifact
          failOnError: true
  #
  #
  #
  #
  #
  #
  #
  # - name: Create Release
  #   id: create_release
  #   uses: actions/create-release@latest
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   with:
  #     tag_name: ${{  steps.package-version.outputs.version }}
  #     release_name: ${{  steps.package-version.outputs.version }}
  #     body: See https://turbot.com/v5/docs/releases/cli
  #     draft: false
  #     prerelease: false
  # - name: Upload Mac Release Asset
  #   uses: actions/upload-release-asset@v1
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   with:
  #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
  #     asset_path: dist/turbot_cli_${{ steps.package-version.outputs.version }}-beta.2_darwin_amd64.zip
  #     asset_name: urbot_cli_${{ steps.package-version.outputs.version }}-beta.2_darwin_amd64.zip
  #     asset_content_type: application/zip
  # - name: Upload Linux Release Asset
  #   uses: actions/upload-release-asset@v1
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   with:
  #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
  #     asset_path: dist/turbot_cli_${{ steps.package-version.outputs.version }}-beta.2_linux_amd64.zip
  #     asset_name: urbot_cli_${{ steps.package-version.outputs.version }}-beta.2_linux_amd64.zip
  #     asset_content_type: application/zip
  # - name: Upload Windows Release Asset
  #   uses: actions/upload-release-asset@v1
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   with:
  #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
  #     asset_path: dist/turbot_cli_${{ steps.package-version.outputs.version }}-beta.2_windows_amd64.zip
  #     asset_name: urbot_cli_${{ steps.package-version.outputs.version }}-beta.2_windows_amd64.zip
  #     asset_content_type: application/zip
